name: Continuous Integration

on:
    push:
        branches:
            - 'main'

env:
    CI: true

jobs:
    continuous-integration:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout current commit
              uses: actions/checkout@v2

            - name: Use Node.js 16
              uses: actions/setup-node@v1
              with:
                  node-version: '16'

            - name: Cache NPM dependencies
              id: npm_cache
              uses: actions/cache@v2
              with:
                  path: '**/node_modules'
                  key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

            - name: Install NPM dependencies
              if: steps.npm_cache.outputs.cache-hit != 'true'
              run: npm ci

            - name: Typecheck files
              run: npm run typecheck

            - name: Lint files
              run: npm run lint
